version: '3.8'

services:
  app:
    build: ./app
    ports:
      - "8080:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=so2db
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: so2db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: so2password
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data:
